# Generated by Django 3.1.5 on 2021-01-06 11:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rosliny',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gatunek', models.CharField(max_length=20)),
                ('wzrost', models.IntegerField()),
                ('mrozoodporne', models.BooleanField()),
                ('opis', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Rynek',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('miejscowosc', models.CharField(max_length=20)),
                ('cena', models.IntegerField()),
                ('ilosc', models.IntegerField()),
                ('dostepnosc', models.BooleanField()),
                ('rosliny', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='rosliny.rosliny')),
            ],
        ),
    ]
